In [3]:
from google.colab import files
uploaded = files.upload()

Saving database.csv to database.csv

In [4]:
import pandas as pd

In [17]:
df1 = pd.read_csv('database.csv')

In [18]:
df2 = df1[:1000] #slicing
df2.to_csv('significant_earthquake.csv')

In [19]:
df2 = pd.read_csv('significant_earthquake.csv')

In [20]:
df2=pd.read_csv('significant_earthquake.csv')

In [21]:
df2.head()

,Unnamed: 0,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [22]:
df2.drop(['Unnamed: 0'],axis=1,inplace=True)

In [23]:
df2.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [24]:
df2.dtypes

Date                           object
Time                           object
Latitude                      float64
Longitude                     float64
Type                           object
Depth                         float64
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Type                 object
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
ID                             object
Source                         object
Location Source                object
Magnitude Source               object
Status                         object
dtype: object

In [28]:
df2['Latitude'].dtypes

dtype('float64')

In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1000 non-null   object
 1   Time                        1000 non-null   object
 2   Latitude                    1000 non-null   float64
 3   Longitude                   1000 non-null   float64
 4   Type                        1000 non-null   object
 5   Depth                       1000 non-null   float64
 6   Depth Error                 4 non-null      float64
 7   Depth Seismic Stations      4 non-null      float64
 8   Magnitude                   1000 non-null   float64
 9   Magnitude Type              1000 non-null   object
 10  Magnitude Error             3 non-null      float64
 11  Magnitude Seismic Stations  4 non-null      float64
 12  Azimuthal Gap               4 non-null      float64
 13  Horizontal Distance         3 non-null      float64
 14  Horizontal Error            4 non-null      float64
 15  Root Mean Square            4 non-null      float64
 16  ID                          1000 non-null   object
 17  Source                      1000 non-null   object
 18  Location Source             1000 non-null   object
 19  Magnitude Source            1000 non-null   object
 20  Status                      1000 non-null   object
dtypes: float64(12), object(9)
memory usage: 164.2+ KB

In [30]:
df2=df2.copy()
df2['Latitude']=df2['Latitude'].astype('int64')
df2.dtypes

Date                           object
Time                           object
Latitude                        int64
Longitude                     float64
Type                           object
Depth                         float64
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Type                 object
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
ID                             object
Source                         object
Location Source                object
Magnitude Source               object
Status                         object
dtype: object

In [31]:
df2.dtypes

Date                           object
Time                           object
Latitude                        int64
Longitude                     float64
Type                           object
Depth                         float64
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Type                 object
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
ID                             object
Source                         object
Location Source                object
Magnitude Source               object
Status                         object
dtype: object

In [32]:
df2["Date"]=pd.to_datetime(df2["Date"],format='%m/%d/%Y')

In [33]:
df2.dtypes

Date                          datetime64[ns]
Time                                  object
Latitude                               int64
Longitude                            float64
Type                                  object
Depth                                float64
Depth Error                          float64
Depth Seismic Stations               float64
Magnitude                            float64
Magnitude Type                        object
Magnitude Error                      float64
Magnitude Seismic Stations           float64
Azimuthal Gap                        float64
Horizontal Distance                  float64
Horizontal Error                     float64
Root Mean Square                     float64
ID                                    object
Source                                object
Location Source                       object
Magnitude Source                      object
Status                                object
dtype: object

In [34]:
df2.head(5)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,1965-01-02,13:44:18,19,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,1965-01-04,11:29:49,1,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,1965-01-05,18:05:58,-20,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,1965-01-08,18:49:43,-59,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,1965-01-09,13:32:50,11,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [36]:
df2["Date"][1]-df2["Date"][0] #find date difference

Timedelta('2 days 00:00:00')

In [37]:
df2['Date'][1]

Timestamp('1965-01-04 00:00:00')

In [39]:
df2["Date"][1].day

4

In [40]:
df2["Date"][1].month

1

In [41]:
df2["Date"][1].year

1965

In [42]:
decimals=df2.select_dtypes('float')
decimals.head()

,Longitude,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square
0,145.616,131.6,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN
1,127.352,80.0,NaN,NaN,5.8,NaN,NaN,NaN,NaN,NaN,NaN
2,-173.972,20.0,NaN,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN
3,-23.557,15.0,NaN,NaN,5.8,NaN,NaN,NaN,NaN,NaN,NaN
4,126.427,15.0,NaN,NaN,5.8,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
decimals.dtypes

Longitude                     float64
Depth                         float64
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
dtype: object

In [46]:
number_data=df2.select_dtypes(exclude='object')

In [47]:
number_data.head()

,Date,Latitude,Longitude,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square
0,1965-01-02,19,145.616,131.6,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1965-01-04,1,127.352,80.0,NaN,NaN,5.8,NaN,NaN,NaN,NaN,NaN,NaN
2,1965-01-05,-20,-173.972,20.0,NaN,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN
3,1965-01-08,-59,-23.557,15.0,NaN,NaN,5.8,NaN,NaN,NaN,NaN,NaN,NaN
4,1965-01-09,11,126.427,15.0,NaN,NaN,5.8,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
number_data.dtypes

Date                          datetime64[ns]
Latitude                               int64
Longitude                            float64
Depth                                float64
Depth Error                          float64
Depth Seismic Stations               float64
Magnitude                            float64
Magnitude Error                      float64
Magnitude Seismic Stations           float64
Azimuthal Gap                        float64
Horizontal Distance                  float64
Horizontal Error                     float64
Root Mean Square                     float64
dtype: object

In [49]:
dtypes_dict={"Depth":"object",}

In [51]:
df3=pd.read_csv('significant_earthquake.csv', dtype=dtypes_dict)

In [52]:
df3.dtypes

Unnamed: 0                      int64
Date                           object
Time                           object
Latitude                      float64
Longitude                     float64
Type                           object
Depth                          object
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Type                 object
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
ID                             object
Source                         object
Location Source                object
Magnitude Source               object
Status                         object
dtype: object

In [53]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1000 non-null   int64
 1   Date                        1000 non-null   object
 2   Time                        1000 non-null   object
 3   Latitude                    1000 non-null   float64
 4   Longitude                   1000 non-null   float64
 5   Type                        1000 non-null   object
 6   Depth                       1000 non-null   object
 7   Depth Error                 4 non-null      float64
 8   Depth Seismic Stations      4 non-null      float64
 9   Magnitude                   1000 non-null   float64
 10  Magnitude Type              1000 non-null   object
 11  Magnitude Error             3 non-null      float64
 12  Magnitude Seismic Stations  4 non-null      float64
 13  Azimuthal Gap               4 non-null      float64
 14  Horizontal Distance         3 non-null      float64
 15  Horizontal Error            4 non-null      float64
 16  Root Mean Square            4 non-null      float64
 17  ID                          1000 non-null   object
 18  Source                      1000 non-null   object
 19  Location Source             1000 non-null   object
 20  Magnitude Source            1000 non-null   object
 21  Status                      1000 non-null   object
dtypes: float64(11), int64(1), object(10)
memory usage: 172.0+ KB

In [56]:
dtypes1={"Type":"category","Status":"category","Source":"category","Location Source":"category","Magnitude Source":"category","Magnitude Type":"category"}
df4=pd.read_csv('significant_earthquake.csv', dtype=dtypes1, parse_dates=['Date','Time'])

/tmp/ipykernel_795/4037549035.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df4=pd.read_csv('significant_earthquake.csv', dtype=dtypes1, parse_dates=['Date','Time'])